<a href="https://colab.research.google.com/github/wonjae124/Pytorch-tutorial/blob/main/eugeniaring_Pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch_array = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print("Tensor array:\n\n",torch_array)

import numpy as np
numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n Numpy array: \n\n",numpy_array)



Tensor array:

 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

 Numpy array: 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
np_rand = np.random.rand(3,3)
print("Random matrix with Numpy : \n")
print(np_rand, "\n")
print(np_rand.shape)

torch_rand = torch.rand(3,3)
print("\n Random matrix with Pytorch: \n")
print(torch_rand,"\n")
print(torch_rand.shape)

#numpy의 기본단위는 identity이지만 tensor의 기본단위는 eye이다.

Random matrix with Numpy : 

[[0.64038338 0.48505205 0.28905143]
 [0.59688311 0.88562907 0.09028473]
 [0.05135432 0.99013898 0.23101317]] 

(3, 3)

 Random matrix with Pytorch: 

tensor([[0.4584, 0.5789, 0.0600],
        [0.5608, 0.1561, 0.8447],
        [0.6893, 0.4694, 0.0505]]) 

torch.Size([3, 3])


In [6]:
np_zeros = np.zeros((3,3))
print(np_zeros,'\n')
torch_zeros = torch.zeros(3,3)
print(torch_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
np_ones = np.ones((3,3))
print(np_ones,'\n')
torch_ones = torch.ones(3,3)
print(torch_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [9]:
np_id = np.identity(3)
print(np_id,'\n')
torch_id = torch.eye(3)
print(torch_id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [11]:
np_a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np_a2 = np.array([[2,3],[2,3],[2,3]])
print(np.dot(np_a1,np_a2),'\n')

#2dimension인 경우의 Matrix_multiplication
torch_a1 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) # 3X3
torch_a2 = torch.tensor([[2,3],[2,3],[2,3]]) # 3X2 
print(torch.mm(torch_a1,torch_a2)) # (3X3)*(3X2) = 3X2 

[[12 18]
 [30 45]
 [48 72]] 

tensor([[12, 18],
        [30, 45],
        [48, 72]])


In [12]:
print(np.multiply(np_a1,2),'\n')
print(torch_a1*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])


In [13]:
torch_a1 = torch.from_numpy(np_a1)
print(type(torch_a1))

np_a1 = torch_a1.numpy()
print(type(np_a1))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [16]:
#Define operations

x1 = torch.tensor([2.0], requires_grad=True).float()
z1 = x1
x2 = torch.tensor([2.0], requires_grad=True).float()
z2 = x2**2
x3 = torch.tensor([2.0], requires_grad=True).float()
z3 = x3**3

#Autograd
z1.backward() # dz1/dx1 = 1
z2.backward() # dz2/dx2 = 2*(x2)
z3.backward() # dz3/dx3 = 3*  ( (x3)**2 ) 


print('dz1/dx1 evaluated in %f: %f'% (x1, x1.grad)) = 1
print('dz2/dx2 evaluated in %f: %f'% (x2, x2.grad)) = 2*2 = 4 
print('dz3/dx3 evaluated in %f: %f'% (x3, x3.grad)) = 3*(2**2) = 3*4 = 12


dz1/dx1 evaluated in 2.000000: 1.000000
dz2/dx2 evaluated in 2.000000: 4.000000
dz3/dx3 evaluated in 2.000000: 12.000000


In [23]:
#1행 10열이면 10개의 뉴런을 가지고 있음

import torch

def sigm(x):
    return 1/(1+torch.exp(-x))

torch.manual_seed(7)

inputs = torch.randn((1,10))
w1 = torch.randn_like(inputs)
b1 = torch.randn((1,1))
#matmul(input,other)은 dot_product(스칼라 생성)이 가능한 matrix multipliaction임.
output = sigm(torch.matmul(inputs, w1)+b1) 

RuntimeError: ignored

In [24]:
import torch

def sigm(x):
    return 1/(1+torch.exp(-x))
    
torch.manual_seed(7)

inputs = torch.randn((1,10))
w1 = torch.randn_like(inputs)
b1 = torch.randn((1,1))

output = sigm(torch.matmul(inputs,w1)+b1) #dotproduct

RuntimeError: ignored

In [35]:
w1.reshape(10,1)
output = sigm(torch.matmul(inputs,w1)+b1) #dotproduct

w1.view(10,1)
output = sigm(torch.matmul(inputs,w1)+b1)
print(output) #return new tensor

w1.resize_(10,1) #return same tensor

print(w1)

tensor([[0.3030]])
tensor([[0.3177],
        [0.1328],
        [0.1373],
        [0.2405],
        [1.3955],
        [1.3470],
        [2.4382],
        [0.2028],
        [2.4505],
        [2.0256]])
tensor([[0.3030]])
tensor([[0.3177],
        [0.1328],
        [0.1373],
        [0.2405],
        [1.3955],
        [1.3470],
        [2.4382],
        [0.2028],
        [2.4505],
        [2.0256]])
tensor([[0.3177],
        [0.1328],
        [0.1373],
        [0.2405],
        [1.3955],
        [1.3470],
        [2.4382],
        [0.2028],
        [2.4505],
        [2.0256]])


In [41]:
print(w1.reshape(10,1).shape)

torch.Size([10, 1])


In [40]:
print(w1.view(10,1).shape)

torch.Size([10, 1])


In [42]:
print(w1.resize_(10,1).shape)

torch.Size([10, 1])


In [48]:
import torch

input_layer = torch.rand(10)
print(input_layer.shape)

torch.Size([10])


In [45]:
w1 = torch.rand(10,20)  # 10 by 20
b1 = torch.rand(20) 

w2 = torch.rand(20,20)
b2 = torch.rand(20)

w3 = torch.rand(20,10)
b3 = torch.rand(10)

#1D인 input_layer는 행렬곱 이후의 결과에서 차원소멸

h1 = torch.matmul(w1.T,input_layer)+b1 #w1. Transpose -> (20 by 10) X (10) = 20
print("First hidden layer: ")
print(h1, "\n")

h2 = torch.matmul(w2.T, h1)+b2 # 20 by 20 * 20 = 20
print("Second hidden layer:")
print(h2,"\n")

output_layer = torch.matmul(w3.T, h2)+b3 # 10 by 20 * 20 = 10  
print("Output layer:")
print(output_layer)

First hidden layer: 
tensor([2.5463, 1.8689, 2.6849, 2.1683, 2.8530, 3.8888, 1.9605, 2.2965, 2.8485,
        3.7596, 2.9201, 2.4318, 1.9947, 2.9652, 4.2126, 2.4276, 3.0956, 3.2615,
        1.7022, 1.9546]) 

Second hidden layer:
tensor([27.7413, 27.4422, 24.4510, 29.3651, 26.0638, 27.4231, 29.8157, 22.1262,
        22.2745, 29.8625, 26.9475, 36.7071, 26.8643, 26.7665, 20.8730, 29.1281,
        27.8653, 32.1158, 26.6047, 23.5480]) 

Output layer:
tensor([291.9523, 252.2548, 277.2212, 251.4830, 202.9329, 263.9237, 296.7025,
        355.4931, 236.1108, 291.9099])


In [56]:
import torch
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1 = nn.Linear(10,20)
        self.fc2 = nn.Linear(20,20)
        self.out = nn.Linear(20,10)

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.out(x)
        return x

input_layer = torch.rand(10)

net = Net()
result = net(input_layer)
print(result)


tensor([-0.1904,  0.0621,  0.3020,  0.2407, -0.1991, -0.2308, -0.2886, -0.1188,
         0.1559, -0.0771], grad_fn=<AddBackward0>)
