<a href="https://colab.research.google.com/github/wonjae124/Pytorch-tutorial/blob/main/model_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import torch.nn as nn


In [5]:
input = torch.randn(32, 1, 5, 5)

m = nn.Sequential(
    nn.Conv2d(1, 32, 5, 1, 1),
    nn.Flatten(),
    nn.Linear(288,10)
)

output = m(input)
output.size()

torch.Size([32, 10])

In [6]:
m = nn.Sigmoid()
input = torch.randn(2)
output = m(input)

In [7]:
output

tensor([0.7388, 0.7840])

In [9]:
m2 = nn.Softmax()
output2 = m2(input)
output2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  


tensor([0.4379, 0.5621])

In [ ]:
import torch
import torch.nn as nn

device = torch.device('cuda' if torch.cuda.is_available() else 
'cpu')

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.layer = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(16),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2), # 16x16x650
            nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1), # 32x16x650
            nn.ReLU(),
            nn.Dropout2d(0.5),
            nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1), # 64x16x650
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2), # 64x8x325
            nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU()) # 64x8x325

        self.fc = nn.Sequential(
            nn.Linear(64*8*325, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, 1),
        )

        def forward(self, x):
            out = self.layer1(x)
            out = self.layer2(out)
            out = out.reshape(out.size(0), -1)
            out = self.fc(out)
            return out


In [51]:
t = torch.tensor([ [[1, 2],
                   [3, 4]],
                   [[5, 6],
                   [7, 8]]])

print(t.shape)

print('1',torch.flatten(t).shape)
#tensor([1, 2, 3, 4, 5, 6, 7, 8])
print('2-0',torch.flatten(t, start_dim=0, end_dim = -1).shape)
print('2-1', torch.flatten(t, start_dim=0, end_dim = 0).shape)
print('2-2', torch.flatten(t, start_dim=0, end_dim = 1).shape)
print('2-3', torch.flatten(t, start_dim=0, end_dim = 2).shape,'\n')


print('3-0', torch.flatten(t, start_dim=1,end_dim=-1).shape)
#print('3-1', torch.flatten(t, start_dim=1,end_dim=0).shape)
print('3-2', torch.flatten(t, start_dim=1,end_dim=1).shape)
print('3-3', torch.flatten(t, start_dim=1,end_dim=2).shape)

#tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(torch.flatten(t, start_dim=2).shape)
#print(torch.Unflatten(t))


torch.Size([2, 2, 2])
1 torch.Size([8])
2-0 torch.Size([8])
2-1 torch.Size([2, 2, 2])
2-2 torch.Size([4, 2])
2-3 torch.Size([8]) 

3-0 torch.Size([2, 4])
3-2 torch.Size([2, 2, 2])
3-3 torch.Size([2, 4])
torch.Size([2, 2, 2])


In [30]:
 input = torch.randn(2, 50)
 # With tuple of ints
 m = nn.Sequential(
     nn.Linear(50, 50),
     nn.Unflatten(1, (2, 5, 5))
 )
 output = m(input)
 output.size()

torch.Size([2, 2, 5, 5])